# -*- coding: utf-8 -*-
"""Dữ liệu kế hoạch dự án PharmaDash dùng chung cho file Excel và file Word (bản nháp do AI đề xuất)."""
import datetime as dt

START = dt.date(2026, 10, 5)      # Thứ Hai
DEADLINE = dt.date(2026, 12, 31)  # hạn go-live theo yêu cầu khách hàng
BUDGET = 250_000_000
CONTINGENCY = 0.10

# (mã, cấp, tên, sản phẩm bàn giao, vai trò, giờ công) – giờ công chỉ nhập ở cấp 3
WBS = [
    ('1.0', 1, 'Quản lý dự án', 'Hồ sơ quản lý dự án', 'PM', None),
    ('1.1', 2, 'Khởi động dự án', 'Charter đã phê duyệt', 'PM', None),
    ('1.1.1', 3, 'Soạn và phê duyệt Project Charter', 'Project Charter có chữ ký Sponsor', 'PM', 16),
    ('1.1.2', 3, 'Họp khởi động (kick-off)', 'Biên bản họp khởi động', 'PM', 8),
    ('1.2', 2, 'Lập kế hoạch', 'Kế hoạch quản lý dự án', 'PM', None),
    ('1.2.1', 3, 'WBS và từ điển WBS', 'WBS 3 cấp + từ điển WBS', 'PM', 16),
    ('1.2.2', 3, 'Lịch dự án và dự toán chi phí', 'File lịch PERT/Gantt, dự toán', 'PM', 16),
    ('1.2.3', 3, 'Kế hoạch quản lý rủi ro', 'Risk Register', 'PM', 12),
    ('1.3', 2, 'Giám sát và kiểm soát', 'Báo cáo tiến độ', 'PM', None),
    ('1.3.1', 3, 'Họp tiến độ hằng tuần và báo cáo (13 tuần)', '13 báo cáo tuần', 'PM', 52),
    ('1.3.2', 3, 'Demo cuối tháng với Giám đốc (3 lần)', '3 biên bản demo, danh sách yêu cầu thay đổi', 'PM', 24),
    ('1.4', 2, 'Kết thúc dự án', 'Hồ sơ đóng dự án', 'PM', None),
    ('1.4.1', 3, 'Nghiệm thu, bàn giao và rút kinh nghiệm', 'Biên bản nghiệm thu, báo cáo bài học', 'PM', 12),

    ('2.0', 1, 'Phân tích yêu cầu', 'Tài liệu SRS đã duyệt', 'BA', None),
    ('2.1', 2, 'Khảo sát nghiệp vụ', 'Báo cáo khảo sát', 'BA', None),
    ('2.1.1', 3, 'Phỏng vấn chủ, quản lý, nhân viên 2 chi nhánh', 'Biên bản phỏng vấn, quy trình hiện tại (AS-IS)', 'BA', 24),
    ('2.1.2', 3, 'Khảo sát phần mềm bán hàng và file Excel tồn kho', 'Báo cáo hiện trạng dữ liệu', 'BA', 16),
    ('2.2', 2, 'Đặc tả yêu cầu', 'SRS', 'BA', None),
    ('2.2.1', 3, 'Viết user story và tiêu chí chấp nhận', 'Product backlog có tiêu chí chấp nhận', 'BA', 32),
    ('2.2.2', 3, 'Đặc tả use case và quy tắc nghiệp vụ (hạn dùng, phân quyền)', 'Tài liệu use case', 'BA', 24),
    ('2.2.3', 3, 'Rà soát và phê duyệt SRS với khách hàng', 'SRS có xác nhận của khách hàng', 'BA', 8),

    ('3.0', 1, 'Thiết kế hệ thống', 'Tài liệu thiết kế', 'BE', None),
    ('3.1', 2, 'Thiết kế kiến trúc và dữ liệu', 'Tài liệu kiến trúc', 'BE', None),
    ('3.1.1', 3, 'Thiết kế kiến trúc hệ thống', 'Sơ đồ kiến trúc', 'BE', 16),
    ('3.1.2', 3, 'Thiết kế CSDL (ERD, tồn kho theo lô)', 'ERD, script tạo CSDL', 'BE', 24),
    ('3.1.3', 3, 'Đặc tả API', 'Danh sách API', 'BE', 16),
    ('3.2', 2, 'Thiết kế giao diện', 'Bộ thiết kế UI', 'FE', None),
    ('3.2.1', 3, 'Design token và wireframe', 'Wireframe, bảng màu, font', 'FE', 32),
    ('3.2.2', 3, 'Mockup các màn hình chính', 'Mockup 8 màn hình', 'FE', 40),

    ('4.0', 1, 'Phát triển Backend', 'API và CSDL hoạt động', 'BE', None),
    ('4.1', 2, 'Nền tảng backend', 'Khung dự án chạy được', 'BE', None),
    ('4.1.1', 3, 'Khung dự án, CSDL, môi trường', 'Mã nguồn khởi tạo, CSDL', 'BE', 16),
    ('4.1.2', 3, 'Xác thực và phân quyền 3 vai trò', 'API đăng nhập, phân quyền', 'BE', 24),
    ('4.2', 2, 'API nghiệp vụ', 'Bộ API nghiệp vụ', 'BE', None),
    ('4.2.1', 3, 'API tổng quan (KPI, biểu đồ, top thuốc)', 'API dashboard', 'BE', 40),
    ('4.2.2', 3, 'API kho thuốc, lô và cảnh báo', 'API kho', 'BE', 40),
    ('4.2.3', 3, 'API đơn hàng và khách hàng', 'API đơn hàng, khách hàng', 'BE', 32),
    ('4.2.4', 3, 'API nhập hàng và nhà cung cấp', 'API nhập hàng', 'BE', 32),
    ('4.2.5', 3, 'API nhân viên, ca làm, lịch', 'API nhân viên', 'BE', 24),
    ('4.3', 2, 'Báo cáo', 'Chức năng xuất báo cáo', 'BE', None),
    ('4.3.1', 3, 'Xuất báo cáo CSV/PDF doanh thu, tồn kho', 'File CSV/PDF mẫu', 'BE', 32),
    ('4.4', 2, 'Tích hợp và chuyển đổi dữ liệu', 'Dữ liệu thật trên hệ thống', 'BE', None),
    ('4.4.1', 3, 'Đồng bộ dữ liệu bán hàng từ phần mềm bán hàng hiện có', 'Bộ đồng bộ dữ liệu', 'BE', 60),
    ('4.4.2', 3, 'Chuyển đổi dữ liệu cũ (danh mục, tồn kho, 2 năm bán hàng)', 'Script chuyển đổi + báo cáo đối soát', 'BE', 40),

    ('5.0', 1, 'Phát triển Frontend', 'Giao diện web hoàn chỉnh', 'FE', None),
    ('5.1', 2, 'Khung giao diện', 'Layout và thư viện component', 'FE', None),
    ('5.1.1', 3, 'Layout, sidebar, topbar, đăng nhập', 'Khung ứng dụng', 'FE', 32),
    ('5.1.2', 3, 'Thư viện component dùng chung', 'KpiCard, ChartCard, DataTable...', 'FE', 32),
    ('5.2', 2, 'Màn hình nghiệp vụ', 'Các trang chức năng', 'FE', None),
    ('5.2.1', 3, 'Trang Tổng quan (dashboard)', 'Trang Tổng quan', 'FE', 56),
    ('5.2.2', 3, 'Trang Kho thuốc và cảnh báo', 'Trang Kho thuốc', 'FE', 48),
    ('5.2.3', 3, 'Trang Đơn hàng và Khách hàng', '2 trang', 'FE', 40),
    ('5.2.4', 3, 'Trang Nhập hàng và Nhà cung cấp', 'Trang Nhập hàng', 'FE', 40),
    ('5.2.5', 3, 'Trang Nhân viên, Báo cáo, Cài đặt', '3 trang', 'FE', 40),
    ('5.3', 2, 'Hoàn thiện giao diện', 'Giao diện đạt yêu cầu phi chức năng', 'FE', None),
    ('5.3.1', 3, 'Responsive, dark mode, tối ưu hiệu năng', 'Giao diện chạy tốt trên PC/tablet', 'FE', 24),

    ('6.0', 1, 'Kiểm thử', 'Sản phẩm đạt chất lượng', 'QA', None),
    ('6.1', 2, 'Chuẩn bị kiểm thử', 'Kế hoạch kiểm thử', 'QA', None),
    ('6.1.1', 3, 'Kế hoạch kiểm thử và test case', 'Test plan, bộ test case', 'QA', 32),
    ('6.2', 2, 'Thực thi kiểm thử', 'Báo cáo kiểm thử', 'QA', None),
    ('6.2.1', 3, 'Kiểm thử chức năng', 'Kết quả chạy test case, báo cáo lỗi', 'QA', 64),
    ('6.2.2', 3, 'Kiểm thử phân quyền và bảo mật', 'Báo cáo kiểm thử bảo mật', 'QA', 24),
    ('6.2.3', 3, 'Kiểm thử hiệu năng', 'Báo cáo hiệu năng', 'QA', 16),
    ('6.2.4', 3, 'Sửa lỗi và kiểm thử hồi quy', 'Bản build ổn định', 'FE', 60),
    ('6.3', 2, 'Nghiệm thu', 'Biên bản UAT', 'QA', None),
    ('6.3.1', 3, 'Kiểm thử chấp nhận (UAT) với khách hàng', 'Biên bản UAT đã ký', 'QA', 24),

    ('7.0', 1, 'Triển khai và chuyển giao', 'Hệ thống vận hành chính thức', 'BE', None),
    ('7.1', 2, 'Triển khai', 'Hệ thống trên máy chủ thật', 'BE', None),
    ('7.1.1', 3, 'Chuẩn bị hạ tầng, sao lưu, bảo mật', 'Máy chủ, HTTPS, lịch sao lưu', 'BE', 16),
    ('7.1.2', 3, 'Go-live và chuyển dữ liệu chính thức', 'Hệ thống chạy thật', 'BE', 16),
    ('7.2', 2, 'Đào tạo và hỗ trợ', 'Người dùng sử dụng được', 'BA', None),
    ('7.2.1', 3, 'Tài liệu hướng dẫn sử dụng', 'Hướng dẫn sử dụng theo vai trò', 'BA', 24),
    ('7.2.2', 3, 'Đào tạo người dùng tại 2 chi nhánh', '2 buổi đào tạo, danh sách tham dự', 'BA', 16),
    ('7.2.3', 3, 'Hỗ trợ sau go-live (2 tuần)', 'Nhật ký hỗ trợ', 'BE', 32),
]

# (vai trò, diễn giải, đơn giá VND/giờ) – giả định
RATES = [
    ('PM', 'Quản lý dự án', 180_000),
    ('BA', 'Phân tích nghiệp vụ', 150_000),
    ('BE', 'Lập trình viên backend', 160_000),
    ('FE', 'Lập trình viên frontend (kiêm thiết kế UI)', 150_000),
    ('QA', 'Kiểm thử viên', 120_000),
]

# (khoản mục, diễn giải, số lượng, đơn giá)
OTHER_COSTS = [
    ('Hosting', 'Máy chủ ảo (VPS) năm đầu, 12 tháng', 12, 500_000),
    ('Tên miền + SSL', 'Tên miền .vn và chứng chỉ SSL 1 năm', 1, 1_000_000),
    ('Đào tạo', 'In tài liệu, đi lại cho 2 buổi đào tạo', 2, 1_500_000),
]

# 15 hoạt động chính cho PERT (đơn vị: ngày làm việc)
ACTIVITIES = [
    dict(id='A', name='Khởi động và lập kế hoạch (Charter, WBS, lịch)', wbs='1.1, 1.2', pred=[], o=3, m=5, p=8),
    dict(id='B', name='Khảo sát nghiệp vụ và dữ liệu hiện có', wbs='2.1', pred=['A'], o=4, m=6, p=10),
    dict(id='C', name='Đặc tả yêu cầu (SRS) và phê duyệt', wbs='2.2', pred=['B'], o=4, m=6, p=9),
    dict(id='D', name='Thiết kế kiến trúc, CSDL, API', wbs='3.1', pred=['C'], o=4, m=6, p=10),
    dict(id='E', name='Thiết kế giao diện (wireframe, mockup)', wbs='3.2', pred=['C'], o=5, m=8, p=12),
    dict(id='F', name='Nền tảng backend, xác thực và phân quyền', wbs='4.1', pred=['D'], o=3, m=5, p=8),
    dict(id='G', name='Phát triển API nghiệp vụ', wbs='4.2', pred=['F'], o=14, m=18, p=26),
    dict(id='H', name='Tích hợp phần mềm bán hàng, chuyển đổi dữ liệu', wbs='4.4', pred=['F'], o=8, m=12, p=20),
    dict(id='I', name='Khung giao diện và thư viện component', wbs='5.1', pred=['E'], o=5, m=7, p=10),
    dict(id='J', name='Phát triển các màn hình nghiệp vụ', wbs='5.2, 5.3', pred=['I', 'F'], o=15, m=20, p=28),
    dict(id='K', name='Chức năng xuất báo cáo CSV/PDF', wbs='4.3', pred=['G'], o=3, m=5, p=8),
    dict(id='L', name='Kế hoạch kiểm thử và test case', wbs='6.1', pred=['C'], o=3, m=4, p=6),
    dict(id='M', name='Kiểm thử hệ thống và sửa lỗi', wbs='6.2', pred=['J', 'K', 'H', 'L'], o=8, m=12, p=18),
    dict(id='N', name='Kiểm thử chấp nhận (UAT) và nghiệm thu', wbs='6.3', pred=['M'], o=3, m=5, p=8),
    dict(id='O', name='Go-live, đào tạo người dùng', wbs='7.1, 7.2', pred=['N'], o=3, m=4, p=7),
]

# Rủi ro do AI gợi ý (nhóm cần bổ sung ít nhất 2 rủi ro của riêng mình)
RISKS = [
    dict(id='R01', group='Bên ngoài / Kỹ thuật',
         cause='Phần mềm bán hàng hiện tại của nhà thuốc chưa rõ nhà cung cấp, có thể không có API hoặc không cho xuất dữ liệu tự động',
         event='Không đồng bộ được dữ liệu bán hàng vào PharmaDash đúng hạn',
         impact='Dashboard không có số liệu thật, trễ go-live, mục tiêu "dữ liệu trễ ≤ 1 phút" không đạt',
         xs=4, td=5, strategy='Giảm',
         action='Khảo sát phần mềm bán hàng ngay tuần 1; làm việc với nhà cung cấp phần mềm; chuẩn bị phương án dự phòng nhập file Excel xuất từ phần mềm bán hàng theo lịch (mỗi 15 phút / cuối ca)',
         owner='BE + BA'),
    dict(id='R02', group='Lịch trình',
         cause='Ước lượng PERT cho thấy đường găng dài hơn số ngày làm việc tới hạn chót 31/12',
         event='Dự án không kịp go-live trước hạn',
         impact='Không kịp dùng cho đợt kiểm kê cuối năm và cao điểm Tết, phát sinh chi phí kéo dài',
         xs=4, td=4, strategy='Giảm',
         action='Nén lịch bằng fast-tracking (làm song song FE/BE, kiểm thử theo từng module) và/hoặc crashing (bổ sung nhân lực bán thời gian); cắt tính năng "Có thể có"',
         owner='PM'),
    dict(id='R03', group='Khách hàng / Yêu cầu',
         cause='Chủ nhà thuốc xem demo cuối mỗi tháng và thường phát sinh ý tưởng mới',
         event='Yêu cầu thay đổi, phạm vi phình ra (scope creep)',
         impact='Tăng khối lượng công việc, trễ tiến độ, vượt ngân sách',
         xs=4, td=4, strategy='Tránh',
         action='Thống nhất phạm vi trong Charter/SRS; quy trình kiểm soát thay đổi (Change Request) có đánh giá tác động thời gian – chi phí; đưa yêu cầu mới vào giai đoạn 2',
         owner='PM'),
    dict(id='R04', group='Kỹ thuật / Dữ liệu',
         cause='Dữ liệu cũ quản lý bằng Excel: mã thuốc trùng, thiếu số lô, thiếu hạn dùng, sai đơn vị tính',
         event='Chuyển đổi dữ liệu sai hoặc thiếu',
         impact='Cảnh báo hạn dùng và tồn kho sai, người dùng mất niềm tin vào hệ thống',
         xs=4, td=4, strategy='Giảm',
         action='Viết script kiểm tra chất lượng dữ liệu; làm sạch dữ liệu cùng dược sĩ phụ trách kho; đối soát tồn kho thực tế trước go-live',
         owner='BE + BA'),
    dict(id='R05', group='Con người',
         cause='Chỉ có 1 lập trình viên backend với khối lượng khoảng 460 giờ trên tổng khoảng 520 giờ khả dụng',
         event='Lập trình viên backend quá tải, ốm hoặc nghỉ việc',
         impact='API trễ, kéo theo frontend và kiểm thử trễ (nằm trên đường gần găng)',
         xs=3, td=5, strategy='Giảm',
         action='Lập trình viên frontend hỗ trợ API đơn giản; code review chéo; tài liệu hóa API; theo dõi khối lượng hằng tuần',
         owner='PM'),
    dict(id='R06', group='Bảo mật / Pháp lý',
         cause='Hệ thống chứa thông tin khách hàng (họ tên, SĐT, lịch sử mua thuốc) và giá nhập, lợi nhuận',
         event='Lộ dữ liệu do phân quyền sai hoặc tấn công',
         impact='Vi phạm quy định bảo vệ dữ liệu cá nhân, mất uy tín, rò rỉ bí mật kinh doanh',
         xs=2, td=5, strategy='Giảm',
         action='Phân quyền kiểm tra ở máy chủ; HTTPS; mã hóa mật khẩu; kiểm thử phân quyền riêng; sao lưu có mã hóa',
         owner='BE + QA'),
    dict(id='R07', group='Con người / Khách hàng',
         cause='Nhân viên quen thao tác giấy và Excel, ít thời gian học phần mềm mới',
         event='Người dùng không sử dụng hoặc dùng sai hệ thống',
         impact='Dữ liệu không được cập nhật, hệ thống không mang lại giá trị',
         xs=3, td=3, strategy='Giảm',
         action='Giao diện đơn giản; đào tạo tại từng chi nhánh; chọn 1 người dùng chủ chốt (key user) mỗi chi nhánh',
         owner='BA'),
    dict(id='R08', group='Kỹ thuật',
         cause='Dữ liệu 2 năm bán hàng (hàng trăm nghìn dòng) và truy vấn thống kê phức tạp',
         event='Dashboard phản hồi chậm hơn 2 giây',
         impact='Trải nghiệm kém, không đạt yêu cầu phi chức năng',
         xs=3, td=3, strategy='Giảm',
         action='Tạo chỉ mục CSDL, bảng tổng hợp theo ngày; kiểm thử hiệu năng với dữ liệu thật từ sớm',
         owner='BE'),
    dict(id='R09', group='Khách hàng / Pháp lý',
         cause='Quy định ngành dược (GPP, thuốc kê đơn) có thể yêu cầu lưu trữ hoặc báo cáo đặc thù chưa nêu trong yêu cầu',
         event='Phát sinh yêu cầu bắt buộc muộn',
         impact='Phải làm thêm chức năng, trễ tiến độ',
         xs=2, td=4, strategy='Giảm',
         action='Hỏi rõ với chủ nhà thuốc và dược sĩ phụ trách chuyên môn ngay khi khảo sát; ghi nhận vào SRS',
         owner='BA'),
    dict(id='R10', group='Bên ngoài / Hạ tầng',
         cause='Hệ thống chạy trên máy chủ thuê ngoài, mạng Internet tại chi nhánh không ổn định',
         event='Máy chủ hoặc mạng gặp sự cố',
         impact='Không truy cập được dashboard trong giờ bán hàng',
         xs=2, td=3, strategy='Chuyển giao',
         action='Chọn nhà cung cấp VPS có cam kết SLA 99,9% trong hợp đồng; sao lưu hằng ngày; hướng dẫn phương án xử lý sự cố',
         owner='BE'),
]
